routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/status/{id}/destroy', 'StatusController@destroy')->name('status_destroy');
Route::resource('/status', 'StatusController');

Route::get('/product/{id}/destroy', 'ProductController@destroy')->name('product_destroy');
Route::resource('/product', 'ProductController');

Route::resource('/order', 'OrderController');

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    <div class="list-group">
                        <a href="{{ route('status.index') }}" class="list-group-item list-group-item-action">Статусы</a>
                        <a href="{{ route('product.index') }}" class="list-group-item list-group-item-action">Товары</a>
                        <a href="{{ route('order.index') }}" class="list-group-item list-group-item-action">Заказы</a>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>
@endsection