routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/status/{id}/destroy', 'StatusController@destroy')->name('status_destroy');
Route::resource('/status', 'StatusController');

Route::get('/product/{id}/destroy', 'ProductController@destroy')->name('product_destroy');
Route::resource('/product', 'ProductController');

Route::resource('/order', 'OrderController');

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
	protected $fillable = [
		'name',
		'price',
		'image',
	];

    public function orders()
    {
    	return $this->belongsToMany(Order::class);
    }}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Product;
use App\Http\Requests\ProductRequest;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = Product::paginate(env('PAGE_SIZE', 10));
        return view('product.index', ['data' => $data]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
         return view('product.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ProductRequest $request)
    {
        $data = $request->validated();
        if (isset($data['image'])) {
            $path = $request->file('image')->store('images', 'public');
            unset($data['image']);
            $data['image'] = $path;
        } else {
            $data['image'] = 'images/no_image.png';
        }
        Product::create($data);
        return redirect()->route('product.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function show(Product $product)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function edit(Product $product)
    {
        return view('product.edit', ['product' => $product]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function update(ProductRequest $request, Product $product)
    {
        $data = $request->validated();
        if (isset($data['image'])) {
            $path = $request->file('image')->store('images', 'public');
            unset($data['image']);
            $data['image'] = $path;
        }
        $product->update($data);
        return redirect()->route('product.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $product = Product::find($id);
        if ($product) {
            $product->delete();
        }
        return redirect()->route('product.index');
    }
}

resources/views/product/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
	<h1>Create</h1>
	<form action="{{ route('product.store') }}" method="post" enctype="multipart/form-data">
		{{ csrf_field() }}
		<div class="form-group">
			<label for="name">Name</label>
			<input class="form-control {{ $errors->first('name') == '' ? '' : 'is-invalid' }}" type="text" name="name" id="name">
			<div class="invalid-feedback">
          		{{ $errors->first('name') }}
        	</div>
		</div>
		<div class="form-group">
			<label for="price">Price</label>
			<input class="form-control {{ $errors->first('price') == '' ? '' : 'is-invalid' }}" type="number" name="price" id="price">
			<div class="invalid-feedback">
          		{{ $errors->first('price') }}
        	</div>
		</div>
		<div class="form-group">
			<label for="image">Image</label>
			<input class="form-control" type="file" name="image" id="image">
		</div>
		<button type="submit" class="btn btn-success">Save</button>
	</form>
</div>
@endsection

resources/views/product/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
	<h1>Edit</h1>
	<form action="{{ route('product.update', $product->id) }}" method="post" enctype="multipart/form-data">
		{{ csrf_field() }}
		<input name="_method" type="hidden" value="PUT">
		<div class="form-group">
			<label for="name">Name</label>
			<input class="form-control {{ $errors->first('name') == '' ? '' : 'is-invalid' }}" type="text" name="name" id="name" value="{{ $product->name }}">
			<div class="invalid-feedback">
          		{{ $errors->first('name') }}
        	</div>
		</div>
		<div class="form-group">
			<label for="price">Price</label>
			<input class="form-control {{ $errors->first('price') == '' ? '' : 'is-invalid' }}" type="number" name="price" id="price" value="{{ $product->price }}">
			<div class="invalid-feedback">
          		{{ $errors->first('price') }}
        	</div>
		</div>
		<div class="form-group">
			<label for="image">Image</label>
			<input class="form-control" type="file" name="image" id="image">
			<img src="{{ url('/storage/' . $product->image) }}" class="img-fluid img-thumbnail mt-2" width="200">
		</div>
		<button type="submit" class="btn btn-success">Save</button>
	</form>
</div>
@endsection

resources/views/product/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
	<a href="{{ route('product.create') }}">Создать</a>
	<h1>Товары</h1>
	<table class="table">
  		<thead>
    		<tr>
      			<th scope="col">#</th>

      			<th scope="col">Name</th>
            <th scope="col">Price</th>

      			<th scope="col">Edit</th>
      			<th scope="col">Delete</th>
    		</tr>
  		</thead>
  		<tbody>
			@foreach ($data as $product)
    		<tr>
    			<td>{{ $product->id }}</td>
    			<td>{{ $product->name }}</td>
          <td>{{ $product->price }}</td>
    			<td>
    				<a href="{{ route('product.edit', $product->id) }}">Изменить</a>
    			</td>
    			<td>
    				<a href="{{ route('product_destroy', $product->id) }}">Удалить</a>
    			</td>
    		</tr>
			@endforeach
		</tbody>
	</table>
  {{ $data->links() }}
</div>
@endsection

resources/views/product/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
	<h1>{{ $status->name }}</h1>
    <p>{{ $status->name }} with ID {{ $status->id }}</p>
</div>
@endsection