routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/status/{id}/destroy', 'StatusController@destroy')->name('status_destroy');
Route::resource('/status', 'StatusController');

Route::get('/product/{id}/destroy', 'ProductController@destroy')->name('product_destroy');
Route::resource('/product', 'ProductController');

Route::resource('/order', 'OrderController');

app/Status.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Status extends Model
{
	protected $fillable = [
		'name',
	];

    public function orders()
    {
    	return $this->hasMany(Order::class);
    }
}

app/Http/Controllers/StatusController.php
<?php

namespace App\Http\Controllers;

use App\Status;
use App\Http\Requests\StatusRequest;

class StatusController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = Status::paginate(env('PAGE_SIZE', 10));
        return view('status.index', ['data' => $data]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('status.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StatusRequest $request)
    {
        $data = $request->validated();
        Status::create($data);
        return redirect()->route('status.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Status  $status
     * @return \Illuminate\Http\Response
     */
    public function show(Status $status)
    {
        return view('status.show', ['status' => $status]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Status  $status
     * @return \Illuminate\Http\Response
     */
    public function edit(Status $status)
    {
        return view('status.edit', ['status' => $status]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Status  $status
     * @return \Illuminate\Http\Response
     */
    public function update(StatusRequest $request, Status $status)
    {
        $status->update($request->all());
        return redirect()->route('status.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Status  $status
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $status = Status::find($id);
        if ($status) {
            $status->delete();
        }
        return redirect()->route('status.index');
    }
}

resources/views/status/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
	<h1>Create</h1>
	<form action="{{ route('status.store') }}" method="post">
		{{ csrf_field() }}
		<div class="form-group">
			<label for="name">Name</label>
			<input class="form-control {{ $errors->first('name') == '' ? '' : 'is-invalid' }}" type="text" name="name" id="name">
			<div class="invalid-feedback">
          		{{ $errors->first('name') }}
        	</div>
		</div>
		<button class="btn btn-success">Save</button>
	</form>
</div>
@endsection

resources/views/status/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
	<h1>Edit</h1>
	<form action="{{ route('status.update', $status->id) }}" method="post">
		{{ csrf_field() }}
		<input name="_method" type="hidden" value="PUT">
		<div class="form-group">
			<label for="name">Name</label>
			<input class="form-control {{ $errors->first('name') == '' ? '' : 'is-invalid' }}" type="text" name="name" id="name" value="{{$status->name}}">
			<div class="invalid-feedback">
          		{{ $errors->first('name') }}
        	</div>
		</div>
		<button class="btn btn-success">Save</button>
	</form>
</div>
@endsection

resources/views/status/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
	<a href="{{ route('status.create') }}">Создать</a>
	<h1>Статусы</h1>
	<table class="table">
  		<thead>
    		<tr>
      			<th scope="col">#</th>
      			<th scope="col">Name</th>
      			<th scope="col">Edit</th>
      			<th scope="col">Delete</th>
    		</tr>
  		</thead>
  		<tbody>
			@foreach ($data as $status)
    		<tr>
    			<td>{{ $status->id }}</td>
    			<td>{{ $status->name }}</td>
    			<td>
    				<a href="{{ route('status.edit', $status->id) }}">Изменить</a>
    			</td>
    			<td>
    				<a href="{{ route('status_destroy', $status->id) }}">Удалить</a>
    			</td>
    		</tr>
			@endforeach
		</tbody>
	</table>
  {{ $data->links() }}
</div>
@endsection

resources/views/status/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
	<h1>{{ $status->name }}</h1>
    <p>{{ $status->name }} with ID {{ $status->id }}</p>
</div>
@endsection