routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/status/{id}/destroy', 'StatusController@destroy')->name('status_destroy');
Route::resource('/status', 'StatusController');

Route::get('/product/{id}/destroy', 'ProductController@destroy')->name('product_destroy');
Route::resource('/product', 'ProductController');

Route::resource('/order', 'OrderController');

app/Order.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Order extends Model
{
	protected $fillable = [
		'first_name',
		'last_name',
		'phone',
        'price',
        'status_id',
	];

    public function status()
    {
    	return $this->belongsTo(Status::class);
    }

    public function products()
    {
    	return $this->belongsToMany(Product::class)->withPivot('count');
    }
}

app/Http/Controllers/OrderController.php
<?php

namespace App\Http\Controllers;

use App\Order;
use App\Status;
use App\Product;
use App\Http\Requests\OrderRequest;
use DB;

class OrderController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = Order::paginate(env('PAGE_SIZE', 10));
        return view('order.index', ['data' => $data]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $statuses = Status::all();
        $products = Product::all();
        return view('order.create', ['statuses' => $statuses, 'products' => $products]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(OrderRequest $request)
    {
        $data = $request->validated();
        $data['price'] = 0;
        $order = Order::create($data);
        return redirect()->route('order.edit', $order->id);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Order  $order
     * @return \Illuminate\Http\Response
     */
    public function show(Order $order)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Order  $order
     * @return \Illuminate\Http\Response
     */
    public function edit(Order $order)
    {
        $statuses = Status::all();
        $products = Product::all();
        return view('order.edit', ['order' => $order, 'statuses' => $statuses, 'products' => $products]);

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Order  $order
     * @return \Illuminate\Http\Response
     */
    public function update(OrderRequest $request, Order $order)
    {
        $data = $request->validated();

        $total = 0;
        foreach ($order->products as $product) {
            $total += $product->price * $product->pivot->count;
        }

        if ($data['is_add_product'] == 'true' && !is_null($data['count'])) {
            DB::table('order_product')->insert([
                'order_id' => $order->id,
                'product_id' => (int)($data['product']),
                'count' => $data['count'],
            ]);

            $product = Product::find((int)($data['product']));
            $total += $product->price * $data['count'];
        }

        $data['price'] = $total;
        $order->update($data);
        return redirect()->route('order.edit', $order->id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Order  $order
     * @return \Illuminate\Http\Response
     */
    public function destroy(Order $order)
    {
        //
    }
}

resources/views/order/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
	<h1>Create</h1>
	<form action="{{ route('order.store') }}" method="post" enctype="multipart/form-data">
		{{ csrf_field() }}
		<div class="form-group">
			<label for="first_name">First Name</label>
			<input class="form-control {{ $errors->first('first_name') == '' ? '' : 'is-invalid' }}" type="text" name="first_name" id="first_name">
			<div class="invalid-feedback">
          		{{ $errors->first('first_name') }}
        	</div>
		</div>
		<div class="form-group">
			<label for="last_name">Last Name</label>
			<input class="form-control {{ $errors->first('last_name') == '' ? '' : 'is-invalid' }}" type="text" name="last_name" id="last_name">
			<div class="invalid-feedback">
          		{{ $errors->first('last_name') }}
        	</div>
		</div>
		<div class="form-group">
			<label for="phone">Phone</label>
			<input class="form-control {{ $errors->first('phone') == '' ? '' : 'is-invalid' }}" type="number" name="phone" id="phone">
			<div class="invalid-feedback">
          		{{ $errors->first('phone') }}
        	</div>
		</div>
		<div class="form-group">
		    <label for="status_id">Status</label>
		    <select class="form-control {{ $errors->first('status_id') == '' ? '' : 'is-invalid' }}" id="status_id" name="status_id">
		    	@foreach ($statuses as $status)
		    		<option value="{{$status->id}}">{{$status->name}}</option>
		        @endforeach
		    </select>
		    <div class="invalid-feedback">
          		{{ $errors->first('status_id') }}
        	</div>
		</div>

		<button type="submit" class="btn btn-success">Save</button>
	</form>
</div>
@endsection

resources/views/order/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
	<h1>Edit</h1>
	<form action="{{ route('order.update', $order->id) }}" method="post" enctype="multipart/form-data" id="my_form">
		{{ csrf_field() }}
		<input name="_method" type="hidden" value="PUT">
		<input name="is_add_product" id="is_add_product" type="hidden" value="false">

		<div class="form-group">
			<label for="first">First Name</label>
			<input class="form-control" type="text" name="first_name" id="first_name" value="{{ $order->first_name }}">
		</div>
		<div class="form-group">
			<label for="last">Last Name</label>
			<input class="form-control" type="text" name="last_name" id="last_name" value="{{ $order->last_name }}">
		</div>
		<div class="form-group">
			<label for="phone">Phone</label>
			<input class="form-control" type="number" name="phone" id="phone" value="{{ $order->phone }}">
		</div>
		<div class="form-group">
			<label for="price">Price</label>
			<input class="form-control" type="number" name="price" id="price" value="{{ $order->price }}" disabled>
		</div>
		<div class="form-group">
		    <label for="status_id">Status</label>
		    <select class="form-control" id="status_id" name="status_id">
		    	@foreach ($statuses as $status)
		    		@if ($order->status_id == $status->id)
		      			<option selected value="{{$status->id}}">{{$status->name}}</option>
		      		@else
		      			<option value="{{$status->id}}">{{$status->name}}</option>
		      		@endif
		        @endforeach
		    </select>
		</div>
		<h2>Products</h2>
		<table class="table table-sm">
		  	<thead>
			    <tr>
			      	<th scope="col">Name</th>
			      	<th scope="col">Count</th>
			      	<th scope="col">Price</th>
			      	<th scope="col">Cost</th>
			    </tr>
		  	</thead>
		  	<tbody>
		  		@foreach ($order->products as $product)
		    	<tr>
		      		<th scope="row">{{$product->name}}</th>
		      		<td>{{$product->pivot->count}}</td>
		      		<td>{{$product->price}}</td>
		      		<td>{{$product->pivot->count * $product->price}}</td>
		    	</tr>
		    	@endforeach
		  	</tbody>
		</table>
		<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#add_product">
 			Add product
		</button>

		<div class="modal" id="add_product">
			<div class="modal-dialog">
			    <div class="modal-content">
				    <div class="modal-header">
				        <h5 class="modal-title">Add Product</h5>
				        <button type="button" class="close" data-dismiss="modal">
				          	<span aria-hidden="true">&times;</span>
				        </button>
				    </div>
			      	<div class="modal-body">
			        	<div class="form-group">
						    <label for="product">Select Product</label>
						    <select class="form-control" id="product" name="product">
						    	@foreach ($products as $product)
						      		<option value="{{$product->id}}">{{$product->name}}</option>
						        @endforeach
						    </select>
						</div>

						<div class="form-group">
							<label for="count">Count</label>
							<input class="form-control" type="number" name="count" id="count">
						</div>
			      	</div>
			      	<div class="modal-footer">
			        	<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
			        	<button type="button" class="btn btn-primary" onclick="document.getElementById('is_add_product').value='true'; document.getElementById('my_form').submit(); document.getElementById('is_add_product').innerHtml='false';">Add</button>
			        </div>
			    </div>
		    </div>
		</div>

		<button type="submit" class="btn btn-success">Save</button>
	</form>

</div>
@endsection

resources/views/order/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
	<a href="{{ route('order.create') }}">Создать</a>
	<h1>Заказы</h1>
	<table class="table">
  		<thead>
    		<tr>
      			<th scope="col">#</th>

      			<th scope="col">First Name</th>
            <th scope="col">Last Name</th>

            <th scope="col">Phone</th>

            <th scope="col">Price</th>
            <th scope="col">Status</th>
      			<th scope="col">Edit</th>
    		</tr>
  		</thead>
  		<tbody>
			@foreach ($data as $order)
    		<tr>
    			<td>{{ $order->id }}</td>
    			<td>{{ $order->first_name}}</td>
          <td>{{ $order->last_name}}</td>
          <td>{{ $order->phone }}</td>
          <td>{{ $order->price }}</td>
          <td>{{ $order->status->name }}</td>
    			<td>
    				<a href="{{ route('order.edit', $order->id) }}">Изменить</a>
    			</td>
    		</tr>
			@endforeach
		</tbody>
	</table>
  {{ $data->links() }}
</div>
@endsection

resources/views/order/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
	<h1>{{ $status->name }}</h1>
    <p>{{ $status->name }} with ID {{ $status->id }}</p>
</div>
@endsection